export enum USER_ROLES_TYPES {
  SUPER_ADMIN = "SUPER_ADMIN",
  AGENCY_ADMIN = "AGENCY_ADMIN",
  USER = "USER",
}

export enum AGENCY_TYPES {
  EQUAL_PARTS = "EQUAL_PARTS",
  LUMEN = "LUMEN",
  ASSURELY = "ASSURELY",
}
